### ISSUE TITLE
plane-drone docker container error in M1 Mac

### ISSUE THREAD

**Issue by MyCADDev** [drifting-in-space/plane#254]
Hi 
I'm seeing this error when I try to run the sample-config
Any workaround? Seems like a rust / docker / M1 Mac issue - https://docs.rs/notify/latest/notify/

```
$ docker compose up

plane-drone       | Error: Error building cert refresher.
plane-drone       | 
plane-drone       | Caused by:
plane-drone       |     Function not implemented (os error 38)
```

**Comment by paulgb** [comment]
Thanks for tracking this down. Yes, it looks like notify is the issue here. I’ll have an attempt at reproducing this tomorrow and see if it’s an easy fix.

**Comment by MyCADDev** [comment]
I made this change below in certs.ts and rebuilt the drone docker image in Ubuntu20 and now I can use that image on a M1 Mac

```
pub type RecommendedWatcher = PollWatcher;
pub fn recommended_watcher<F>(event_handler: F) -> Result<RecommendedWatcher, Error>
where
    F: EventHandler,
{
    // All recommended watchers currently implement `new`, so just call that.
    RecommendedWatcher::new(event_handler, Config::default())
}

pub struct CertRefresher {
    receiver: Receiver<Option<Arc<CertifiedKey>>>,
    _watcher: RecommendedWatcher,
}
```

**Comment by paulgb** [comment]
I think the root of this issue was that we started using our own build image (to enable build caching), and we were not building an arm64 version of that image. Docker for Mac could run the image through amd64 emulation, but the emulation layer did not implement the filesystem polling APIs that the container expected.

[This PR](https://github.com/drifting-in-space/rust-sccache/pull/2) added an arm64 build to the build image, which works for me. Can you try this and confirm if it works for you? (In a git branch that doesn't have your `certs.rs` change applied)

```
docker pull ghcr.io/drifting-in-space/rust-sccache:latest
docker compose build
docker compose up
```

**Comment by MyCADDev** [comment]
This works - thanks @paulgb !!

**Comment by paulgb** [comment]
Thanks for filing and for confirming, Harish!
