### ISSUE TITLE
Populate `x-forwarded-for` Header in Proxy

### ISSUE THREAD

**Issue by t-moe** [drifting-in-space/plane#296]
Currently, there is no way for the launched container to figure out the IP-Address of the original requester.
Typically, proxies set the `x-forwarded-for` header for that.

(Hi Paul, this is just a suggestion for an enhancement. We can easily live without it right now, or I could add it myself  when we need it. )

**Comment by paulgb** [comment]
Good catch, yes we should be setting this. It's surprisingly a bit tricky to feed the IP through tower but it's doable.

I think the best practice here is that the value is:
- If `x-forwarded-for` is present on the request, pass it on unmodified
- Otherwise, set `x-forwarded-for` to be the IP on the other end of the connection.

Does that sound right?

**Comment by paulgb** [comment]
This is now implemented in the `main` branch with the recent rewrite!
