### ISSUE TITLE
cpu_period still seems to still use seconds instead of miscroseconds

### ISSUE THREAD

**Issue by alecswjo** [drifting-in-space/plane#479]
This commit should have fixed cpu period to be microseconds instead of seconds: #468 

However, making spawn requests using "cpu_period": 1000000 leads to this error: 

> Docker responded with status code 400: CPU cfs period can not be less than 1ms (i.e. 1000) or larger than 1s (i.e. 1000000) state=Loading

Steps:
- pulled the latest plane code into my ec2 instance, confirmed that the latest code had the changes from https://github.com/drifting-in-space/plane/pull/468/commits/645f6841d69d763ac54daddcd78df130584e77a1
- made a spawn request with the following:

```
spawn_message = {
            "cluster": CLUSTER_NAME,
            "max_idle_secs": 300,
            "metadata": {},
            "executable": {
                "image": "kernel-service",
                "env": {},
                "volume_mounts": [vm.dict() for vm in body.volume_mounts],
                "resource_limits": {
                    "memory_limit_bytes": int(MEMORY_LIMIT_BYTES),  # 5GiB in bytes
                    "cpu_period": 1000000,  # Assume a cpu period of 1 second (1 million microseconds)
                    "cpu_period_percent": 50,  # 50% of the cpu_period
                    # "cpu_time_limit": None,
                    # "disk_limit_bytes": None
                },
            },
            "lock": body.lock,
        }
```

- confirmed that the request worked when "cpu_period": 1 instead.

**Comment by paulgb** [comment]
Thanks for reporting this Alec, will look into this!

**Comment by pretentious7** [comment]
Hello!

I've attempted to make this a little easier to reproduce on this branch https://github.com/drifting-in-space/plane/tree/abhi/add-resource-limits-plane-spawn

I started ./dev-nats , ./dev-controller, and ./dev-drone, then ran the following

`./dev-cli.sh spawn --resource-limits '{"cpu_period":1}' plane.test hello-world`
`
which yielded {"message":"CPU cfs period can not be less than 1ms (i.e. 1000) or larger than 1s (i.e. 1000000)"}
on the docker socket (which I'm snooping using socat) as expected.

I suspect your observation is a result of a mismatch between drone and controller version. The result you observed would be expected if the controller was updated but the drone wasn't, since the controller would pass the 1 through to the drone, which would deserialize it as 1 second.

could you post the version of the drone and of the controller?
